name: CI
env:
  SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      #Using npm ci is generally faster than running npm install
      run: |
        cd ReactTestApp/web-app
        npm ci
    - name: Build the app 
      run: |
        cd ReactTestApp/web-app
        npm run build
    - name: Run component tests 
      run: |
        cd ReactTestApp/web-app
        npm run test
    - name: Start the app 
      run: |
        cd ReactTestApp/web-app
        npm start &
        npx wait-on --timeout 60000